### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by marksteadman080592** [TowelSniffer/Anki-Chess-2.0#13]
this doesn't work on anki for me it doesn't show the board it just shows the header

**Comment by TowelSniffer** [comment]
if you see something like this then it is most likely an issue with you PGN/FEN inputs

![image](https://user-images.githubusercontent.com/52064198/114883486-de30ed80-9dfc-11eb-8552-6fc0d6724f8a.png)

you will have to show me what you are putting into the PGN and FEN fields 

otherwise, I could you tell me what version of Anki and the operating system you are on.
