### ISSUE TITLE
It always makes me play as black

### ISSUE THREAD

**Issue by affirmo-nego** [TowelSniffer/Anki-Chess-2.0#18]
It makes me play black pieces even if the last move in the notation is by white
![Screenshot_20220904_112826](https://user-images.githubusercontent.com/108141243/188300586-451bff9e-a8d4-4782-ba13-b48c69659d0d.png)

**Comment by TowelSniffer** [comment]
This is by design actually.

So the way I like to make my cards is to set it so that you are responding to a move. That is If i want to make a card for black then I make the first move in the PGN white and the response is the solution. the last move doesn't matter as the cards will work the same. 

If you wish to change this default behavior then I have made the solution very simple. On the card templates for the frontside there is the line:

```
	document.getElementById("Board").src = `_chess3.0.html?PGN=` + PGN + `&flip=true&backgroundColor=` + backgroundColor + `&handicap=` + handicap + ``;
```

and on the backside ate the bottom: 

```
	document.getElementById("analysisBoard").src = `_ChessTempoViewer.html?PGN=` + PGN + `&flip=true&errorCheck=` + errorCheck + `&backgroundColor=` + backgroundColor + ``;
```

for both of these lines change `flip=true` to `flip=false`. should result in the expected behavior.
