### ISSUE TITLE
Puts me in the position of the losing player

### ISSUE THREAD

**Issue by cademcniven** [TowelSniffer/Anki-Chess-2.0#19]
I'm fairly new to chess as well as its technologies so I might just be doing something stupid here, but I've found when I try to make new cards with this note type it puts me as the wrong player.

I tried using some data from https://github.com/xinyangz/chess-tactics-pgn for this (I've tried other sources too just to check if it was bad data). For example:

```
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "N.N."]
[Black "N.N."]
[Result "1-0"]
[Annotator "T1R"] [SetUp "1"] [FEN "2r2rk1/pp1bqpp1/2nppn1p/2p3N1/1bP5/1PN3P1/PBQPPPBP/3R1RK1 w - - 0 1"] [PlyCount "5"] [EventType "swiss"] 1. Nd5 exd5 (1... hxg5 2. Nxe7+ Nxe7) 2. Bxf6 hxg5 3. Bxe7 1-0
```

![image](https://user-images.githubusercontent.com/17060136/192877537-9ad9aa79-7b50-46ba-9cab-c65e9744633f.png)

This results in white making the first move:

![image](https://user-images.githubusercontent.com/17060136/192877675-960c3f36-dcd0-477c-b951-03ab5a998828.png)

And with white finishing with the advantage:

![image](https://user-images.githubusercontent.com/17060136/192877739-ac5c878e-b961-43c3-bfeb-e0a1d94c0a9c.png)

Unless I'm totally confused (possible), I believe this tactic should be from the perspective of the white player, but I'm not quite sure what needs to be changed for this to happen.

To be clear, this isn't just an issue with this single tactic, but an issue with any data I put into this note type. Any help would be appreciated, thanks

**Comment by TowelSniffer** [comment]
Yo you are the first to be confused by this, I really need to update the documentation but I have been busy/lazy lately...

This is by design actually.

So the way I like to make my cards is to set it so that you are responding to a move. That is If i want to make a card for black then I make the first move in the PGN white and the response is the solution. the last move doesn't matter as the cards will work the same. I make my cards from my personal games rather than using online sourced tactics. 

If you wish to change this default behavior then I have made the solution very simple. On the card templates for the frontside there is the line:

```
	document.getElementById("Board").src = `_chess3.0.html?PGN=` + PGN + `&flip=true&backgroundColor=` + backgroundColor + `&handicap=` + handicap + ``;
```

and on the backside ate the bottom: 

```
	document.getElementById("analysisBoard").src = `_ChessTempoViewer.html?PGN=` + PGN + `&flip=true&errorCheck=` + errorCheck + `&backgroundColor=` + backgroundColor + ``;
```

for both of these lines change `flip=true` to `flip=false`. should result in the expected behavior.
