### ISSUE TITLE
Shogi

### ISSUE THREAD

**Issue by khonkhortisan** [TowelSniffer/Anki-Chess-2.0#20]
https://lishogi.org/study/4XssSDlR
![image](https://user-images.githubusercontent.com/1996449/194782465-e1f5c797-cf51-4eb9-87af-a92efea9513f.png)

**Comment by TowelSniffer** [comment]
Is your question whether or not a similar template could be designed for Shogi? because definitely in theory. This template uses lichess' chessground for the board. Lishogi has it's own open sourced board [shogiground](https://github.com/WandererXII/shogiground). You could set up a template with that rather easily if you know what you are doing. I do not really know what I am doing as I never formally learned any coding other than trial and error in making anki templates, so this would take me way too long for something I probably wont use. My point is that even if you don't code, you'd be surprised what you can achieve with some stubbornness.

As a side note, I did manage to put together a [go template](https://github.com/TowelSniffer/go) for anki if you are interested.
