### ISSUE TITLE
Move can't be done

### ISSUE THREAD

**Issue by amalrajjs** [TowelSniffer/Anki-Chess-2.0#21]
Instead of moves for Sicilian 1.e4 e5 2.Nf3 Nc6, there is an alternative way e2e4 e7e5 g1f3 b8c6. Please add this features too.

**Comment by amalrajjs** [comment]
Moves are in UCI format. Can you add the feature to support UCI?

**Comment by TowelSniffer** [comment]
So the issue is that this template uses [this](https://github.com/mliebelt/pgn-parser) pgn-parser. I initially actually tried to write my own parser but did a really poor job so I am reliant on this library and this is where support for this would need to be added. I'm not really sure how realistic this would be seeing as the library is designed how parse standard PGN format not UCI.
