### ISSUE TITLE
White flashes between cards

### ISSUE THREAD

**Issue by gokberkgunes** [TowelSniffer/Anki-Chess-2.0#33]
It seems like when the cards first load there is a white background appearing for a slight second. It seems like I only have this issue on the desktop version on Anki, on Ankidroid everything works very well. I have seen this problem on the tutorial video as well, which suggests that problem is not appearing just for me.

Frankly, I am not sure if the problem caused by Anki-Chess-2.0 or the Anki desktop. I looked up online for similar problems; sadly, I could not find any concrete information. Is there any way or hack to avoid this issue?

**Comment by TowelSniffer** [comment]
Hi, Sorry for the late response here. So this is an issue with newer versions of anki desktop that also annoys me a lot. This template works by rendering a html iframe, which is important as otherwise the JavaScript will conflict with anki. While the Iframe is loading the default background is white, and I have it detect your anki background colour and change to that. But any delay in the loading will appear as a white flash. 

This wasn't an issue before as I simply made the iframe transparent, but for some reason new versions of anki don't allow transparent Iframes. We would need to open a bug report in anki to solve this.

**Comment by TowelSniffer** [comment]
Last update actually fixes this btw
