### ISSUE TITLE
boardMoves box height CSS + sounds for moves/captures

### ISSUE THREAD

**Issue by atenonai** [TowelSniffer/Anki-Chess-2.0#45]
I had a look at the `ChessTempoViewer.html` file but couldn't quite figure out how to change the boardMoves box sizing. Is it possible to change it so that the height is just auto (based on amount of content) instead of having it fixed and scrollable? 

Changing `.whole.layout-top .moves, .whole.layout-bottom .moves {overflow: visible}` and `#boardMoves {box-shadow: none; background-color: none}` seems to kind of achieve this – the card itself can then be scrolled if there is a lot of content. With Anki in dark mode the text becomes hard to read though, and changing all the text colors seems a bit cumbersome. Is there an easier way to achieve this?

---

Also, a feature request – could piece movement sounds be added for moves/captures? It would be really neat I think (and Event Listeners are probably already present for this?). 

https://github.com/lichess-org/lila/tree/master/public/sound/standard

Thank you for the template, it's amazing.

**Comment by TowelSniffer** [comment]
Last release attempts to fix the boardMoves box to auto adjust to height of the PGN. hopefully it works on all devices, let me know how you go. 

Sound is a good suggestion, something I have wanted to add for a while now. I think it will be the next feature I tackle. thanks for the link.

**Comment by TowelSniffer** [comment]
Yeah so the background colour is set with js. I used to just make the IFrame transparent, but an update removed support for this so I have to manually set it with JavaScript. 

So for consistent results, rather than setting the background colour is CSS, you can try setting it with this variable, which is then sent to the IFrame. 

'''
var background = window.getComputedStyle( document.body ,null).getPropertyValue('background-color');
'''

I will have a play around with it later, but anki can be a bit weird with IFrames. I run into issues like this a lot with anki where the first card to load doesn't work properly. Usually it's because a variable is being set too early/late.

**Comment by TowelSniffer** [comment]
added sound with last release
