### ISSUE TITLE
Drawn annotations issue/support

### ISSUE THREAD

**Issue by atenonai** [TowelSniffer/Anki-Chess-2.0#46]
Currently there seems to be an issue with including drawn annotations when creating notes. Arrows only work if there is a circle present (on any move) for some reason, while circles are never rendered on the board.

_Example A: Arrows with circle present_

- Arrows work and are correctly hidden in the move list. Circles don't work, shows up as plain comments.
```
[FEN "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"]  
1. e4 {[%csl Ge4]} e6 2. d4 d5 {[%cal Bb1c3,Bb1d2,Be4e5,Be4d5]} *
```
  - <img width="600" alt="a" src="https://github.com/user-attachments/assets/9e28b87d-1462-407f-84ac-971d86d606a2">

_Example B: Arrows without circle present_

- Arrows no longer work, now shows up as plain comments.
```
[FEN "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"]   
1. e4 e6 2. d4 d5 {[%cal Bb1c3,Bb1d2,Be4e5,Be4d5]} *
```
  - <img width="600" alt="b" src="https://github.com/user-attachments/assets/01d6d9c2-1095-4e12-91c8-710c5e4e0811">

_Example C: Circle_

- Circle, never works.
```
[FEN "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"]  
1. e4 e6 2. d4 d5 {[%csl Rd4]} *
```
  - <img width="600" alt="c" src="https://github.com/user-attachments/assets/60fb1504-2172-4929-a050-0504d3de03ec">

I'm not sure if drawn annotations is an intended feature? Full support for it would be nice though, especially seeing how it almost works already.

**Comment by TowelSniffer** [comment]
i have never messed around with drawn annotations, though I thinks it's pretty cool so I will see if I can find the fix for this. These cards use lichess' [chessground](https://github.com/lichess-org/chessground) UI so this is a feature of that rather than something I intentionally added. I sort of just frankensteined it together with a bunch of other libraries while teaching myself to code. I am not really sure it this bug is something to do with the version of chessground I am using or some kind of conflict with anki. I plan to add sound over the weekend so I will look into this issue then thanks.

**Comment by TowelSniffer** [comment]
Should be fixed in latest release.
