### ISSUE TITLE
Suggestion: Decouple example decks from card templates deck.

### ISSUE THREAD

**Issue by pwenker** [TowelSniffer/Anki-Chess-2.0#8]
I'd suggest to not include the example decks (tactics, lichess studies) with the card templates. 

The reasons:
1) Users may only be interested in the card templates, to create their own cards.
2) Reversely, users may only be interested in the finished example decks
3) Every time updates to the card templates are made, when users want to get the new card templates they are forced to also import the example decks again.
4) And finally, but most importantly: If you'd create a new repository, or I could also do it if you prefer, we could collect not only your example decks, but also other  finished decks organized, for example, by tactics, endgames, strategical, etc., .... Each deck  could e.g. be added there with the source csv file, and the anki deck itself. Then others could  contribute their own decks there. As one example, I could programmatically add certain high quality `lichess studies` as their own decks.

**Comment by TowelSniffer** [comment]
Yeah this makes sense, point three especially. 

Rather than making a new repository, my current plan was to just include a folder in this repository where we could add decks and their required media in CSV format. Then just have a readme for each with some information and installation instructions (note type etc).

We can also add things like alternate piece themes. 

I'd prefer this to a separate repository tbh but let me know what you think.

**Comment by pwenker** [comment]
Yes, I think you're right that dedicated folders in here would be sufficient and your description sounds good!

**Comment by TowelSniffer** [comment]
Beautiful, I will set this up tonight/tomorrow morning. Another user of the deck just sent me an opening study he ankified so ill add that also
