### ISSUE TITLE
moving by clicking start, end vs dragging piece

### ISSUE THREAD

**Issue by nathanbraun** [TowelSniffer/Anki-Chess-2.0#9]
Hi there, this is an awesome plugin, thanks a lot.

I first used a version a while ago and recently upgraded to 2.0.  Overall it's better (e.g. green when solved, randomly do alternative moves, etc) but one issue is that I find it more cumbersome to have to drag pieces to move them, vs before when I could just click on the piece, then click on the square I wanted it to end up at.

I might just need to get used to it, but if you think about it, clicking on start and stop is (by definition) less work, since you have to do that when dragging too.

Any thoughts re-enabling this or making it an option?  Thanks so much for all your great work!

**Comment by TowelSniffer** [comment]
Hi so first I will say, I'm not really a programmer tbh, my only experience is with making anki templates, so for now this was a feature I had shelved due to mainly a lack of knowledge. This is something I would ideally like to see myself, especially for mobile, but I will just clarify why is was "disabled" in the first place. 

The old templates were an implementation of [lt-pgn-viewer](http://www.lutanho.net/pgn/pgnviewer.html). The new templates use a couple pieces of software, chess.js, chessboard.js, a very nice pgn parser and so on.

The problem is [chessboard.js](https://chessboardjs.com/examples#1000), which is basically the board, only supports drag and drop. I have been following an issue on their GitHub and we may see click to move supported in the future, but for now it isn't. 

Anyway, I only went with chessboard.js because it has good documentation, especially with chess.js integration, but there are other boards out there. Ideally I would use lichess' open source board, but the lack of documentation for it makes it hard for me to integrate.

**Comment by huandney** [comment]
Really, if we could have both options it would be perfect.Mainly because of the ankidroid, as it is not very practical to drag.

**Comment by TowelSniffer** [comment]
https://github.com/ornicar/chessground

That's the open source board lichess uses. It's a better option than chessboard.js and works better on mobile devices, however i can't figure out how to integrate it with chess.js. if someone can help me figure it out than I will implement it.

**Comment by TowelSniffer** [comment]
ok so I managed to modify the [cheesground example](https://github.com/ornicar/chessground-examples/tree/master/src/units) to work as a template for the latest release (if I ever formally learn to code I will design this myself but for now I have wasted enough of my life on this and I'm happy with the results). You get click to move with the latest release and some other upgrades like drawing on the board and highlighted check.
